plugins {
    id 'java'
	id 'application'
    id 'io.qameta.allure' version '4.1.0'
}

group = 'ru.alfabank'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

allure {
    version = '2.29.0' // Версия консольной утилиты для сборки отчета
    adapter {
        frameworks {
            junit5 {
                adapterVersion = '2.35.4' // Версия библиотек для JUnit 5
            }
        }
    }
}

dependencies {
    // 1. Управляем всеми версиями тестов через стабильный JUnit 5 BOM
    testImplementation platform('org.junit:junit-bom:5.11.0')

    // 2. Артефакты JUnit 5 подтягивают правильную версию из BOM автоматически
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // Движок для запуска Test Suites (необходим для Cucumber / Сьютов в JUnit 5)
    testRuntimeOnly 'org.junit.platform:junit-platform-suite-engine'

    // 3. Сторонние библиотеки (бизнес-логика)
    implementation 'net.datafaker:datafaker:2.5.4'
    implementation 'com.github.lalyos:jfiglet:0.0.8'

    // 4. Инструменты тестирования (REST Assured и Cucumber)
    testImplementation 'io.rest-assured:rest-assured:5.5.0'
    testImplementation 'io.cucumber:cucumber-java:7.15.0'
    testImplementation 'io.cucumber:cucumber-junit-platform-engine:7.15.0'
    compileOnly 'org.projectlombok:lombok:1.18.38'
    annotationProcessor 'org.projectlombok:lombok:1.18.38'
    testCompileOnly 'org.projectlombok:lombok:1.18.38'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.38'
    testImplementation 'com.fasterxml.jackson.core:jackson-databind:2.22.2'

    // Актуальная версия Selenide с поддержкой современных версий Java
    testImplementation 'com.codeborne:selenide:7.18.1'
}

test {
    useJUnitPlatform()
}
tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
tasks.withType(JavaExec).configureEach {
    systemProperty 'file.encoding', 'UTF-8'
    systemProperty 'console.encoding', 'UTF-8'
    systemProperty 'stdout.encoding', 'UTF-8'
}

application {
    applicationDefaultJvmArgs = [
        '-Dfile.encoding=UTF-8',
        '-Dconsole.encoding=UTF-8',
        '-Dstdout.encoding=UTF-8'
    ]
}